import os
import shutil
import argparse
from ultralytics import YOLO

def main():
    parser = argparse.ArgumentParser(description="Fine-tune YOLOv8 for emergency vehicles")
    parser.add_argument("--data", type=str, required=True, help="Path to dataset YAML file (e.g. data/emergency_vehicles.yaml)")
    parser.add_argument("--epochs", type=int, default=10, help="Number of training epochs")
    parser.add_argument("--imgsz", type=int, default=640, help="Image size for training")
    args = parser.parse_args()

    if not os.path.exists(args.data):
        raise FileNotFoundError(f"Dataset YAML file not found: {args.data}")

    print("Initializing base YOLO model from yolov8n.pt...")
    model = YOLO("yolov8n.pt")
    print("Successfully loaded base model.")

    # Train the model
    print(f"Starting training for {args.epochs} epochs...")
    results = model.train(data=args.data, epochs=args.epochs, imgsz=args.imgsz, project="runs_kinetica", name="finetune")
    
    # Path to best weights generated by Ultralytics
    # Normally saved in runs_kinetica/finetune/weights/best.pt
    best_weights_src = os.path.join("runs_kinetica", "finetune", "weights", "best.pt")
    
    # Target directory
    target_dir = "weights"
    os.makedirs(target_dir, exist_ok=True)
    target_weights = os.path.join(target_dir, "best.pt")
    
    if os.path.exists(best_weights_src):
        shutil.copy(best_weights_src, target_weights)
        print(f"Training complete. Best weights saved to: {target_weights}")
    else:
        print(f"Training completed but could not find weights at {best_weights_src}. Please check the runs directory.")

if __name__ == "__main__":
    main()
